name: Manual UI Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to run the UI Tests from'
        required: true
        default: 'develop'

jobs:
  test_ui:
    name: Run UI Tests
    uses: ./.github/workflows/ui-test.yml
    with:
      test_branch: github.event.inputs.branch
    secrets: inherit
