name: iOS Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ develop, release/*, main ]
    
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app, run unit tests and send coverage report for branch
    runs-on: macos-13

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Lint
        run: swiftlint --strict
        
      - name: Run staging configuration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
        run: |
          export GEM_HOME=$HOME/.gem
          export GEM_PATH=$HOME/.gem

          # Fixes issue with bundle install
          eval "$(rbenv init - zsh)"
          bundle install
                    
          bundle exec fastlane testWithoutCoverage scheme:"OneLoginStaging" \
            testplan:OneLoginStaging
            
        - name: Run build configuration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
        run: |
          export GEM_HOME=$HOME/.gem
          export GEM_PATH=$HOME/.gem

          # Fixes issue with bundle install
          eval "$(rbenv init - zsh)"
          bundle install
          
          bundle exec fastlane testWithoutCoverage scheme:"OneLoginBuild" \
            testplan:OneLoginBuild
            

      - name: Run UI tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
        run: |
          export GEM_HOME=$HOME/.gem
          export GEM_PATH=$HOME/.gem

          # Fixes issue with bundle install
          eval "$(rbenv init - zsh)"
          bundle install
                    
          bundle exec fastlane testWithoutCoverage scheme:"OneLoginBuild" \
            testplan:OneLoginUI
